const mongoose = require("mongoose");
const Campus = require("../models/Campus");
const dotenv = require("dotenv");
const path = require("path");

dotenv.config();

const campuses = [
	{
		code: 10192,
		name: "Universitas Nahdlatul Ulama Al Ghazali, Cilacap",
		city: "Cilacap",
		province: "Jawa Tengah",
	},
	{
		code: 10191,
		name: "Lembaga Pendidikan dan Pengembangan Profesi Indonesia (LP3I), Medan",
		city: "Medan",
		province: "Sumatera Utara",
	},
	{
		code: 10190,
		name: "Universitas Bung Hatta",
		city: "Padang",
		province: "Sumatera Barat",
	},
	{
		code: 10189,
		name: "Universitas Mathla'ul Anwar Banten",
		city: "Kab. Pandeglang",
		province: "Banten",
	},
	{
		code: 10188,
		name: "STAI Binamadani",
		city: "Kota Tangerang",
		province: "Banten",
	},
	{
		code: 10187,
		name: "Sekolah Tinggi Manajemen Logistik",
		city: "Kab. Bandung",
		province: "Jawa Barat",
	},
	{
		code: 10186,
		name: "Nusa Putra University",
		city: "Kab. Sukabumi",
		province: "Jawa Barat",
	},
	{
		code: 10185,
		name: "Institut Agama Islam Sahid Bogor",
		city: "Kab. Bogor",
		province: "Jawa Barat",
	},
	{
		code: 10184,
		name: "Universitas Muhammadiyah Sumatera Utara",
		city: "Kota Medan",
		province: "Sumatera Utara",
	},
	{
		code: 10183,
		name: "Universitas Teknokrat Indonesia",
		city: "Kota Bandar Lampung",
		province: "Lampung",
	},
	{
		code: 10182,
		name: "Universitas Muhammadiyah Palembang",
		city: "Kota Palembang",
		province: "Sumatera Selatan",
	},
	{
		code: 10181,
		name: "Universitas Tulang Bawang",
		city: "Kota Bandar Lampung",
		province: "Lampung",
	},
	{
		code: 10180,
		name: "Sekolah Tinggi Ilmu Al Quran (STIQ) Kepulauan Riau",
		city: "Kota Batam",
		province: "Kepulauan Riau",
	},
	{
		code: 10179,
		name: "Universitas Mahaputra Muhammad Yamin",
		city: "Kab. Solok",
		province: "Sumatera Barat",
	},
	{
		code: 10178,
		name: "Universitas Respati Yogyakarta",
		city: "Kab. Sleman",
		province: "D.I. Yogyakarta",
	},
	{
		code: 10177,
		name: "Universitas Majalengka (UNMA)",
		city: "Kab. Majalengka",
		province: "Jawa Barat",
	},
	{
		code: 10176,
		name: "Sekolah Tinggi Ilmu Tarbiyah (STIT) Islamic Village",
		city: "Kota Tangerang",
		province: "Banten",
	},
	{
		code: 10175,
		name: "Politeknik Industri Furnitur dan Pengolahan Kayu",
		city: "Kab. Kendal",
		province: "Jawa Tengah",
	},
	{
		code: 10174,
		name: "Universitas Gunadarma",
		city: "Kota Depok",
		province: "Jawa Barat",
	},
	{
		code: 10173,
		name: "Ma'had Aly Jakarta",
		city: "Kota Jakarta Barat",
		province: "D.K.I. Jakarta",
	},
	{
		code: 10172,
		name: "Sekolah Tinggi Agama Islam Muhammadiyah Klaten",
		city: "Kab. Klaten",
		province: "Jawa Tengah",
	},
	{
		code: 10171,
		name: "Institut Informatika dan Bisnis Darmajaya",
		city: "Kota Bandar Lampung",
		province: "Lampung",
	},
	{
		code: 10170,
		name: "Politeknik Pariwisata Batam",
		city: "Kota Batam",
		province: "Kepulauan Riau",
	},
	{
		code: 10169,
		name: "Institut Teknologi PLN",
		city: "Kota Jakarta Barat",
		province: "D.K.I. Jakarta",
	},
	{
		code: 10168,
		name: "STIBA Arraayah Sukabumi",
		city: "Kab. Sukabumi",
		province: "Jawa Barat",
	},
	{
		code: 10167,
		name: "STAI Daarut Tauhiid Bandung",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 10166,
		name: "Universitas Sarjanawiyata Tamansiswa",
		city: "Kota Yogyakarta",
		province: "D.I. Yogyakarta",
	},
	{
		code: 10165,
		name: "Universitas Budi Luhur Jakarta",
		city: "Kota Jakarta Selatan",
		province: "D.K.I. Jakarta",
	},
	{
		code: 10164,
		name: "Universitas Harapan Medan",
		city: "Kota Medan",
		province: "Sumatera Utara",
	},
	{
		code: 10163,
		name: "STIKES Pelita Ilmu Depok",
		city: "Kota Depok",
		province: "Jawa Barat",
	},
	{
		code: 10162,
		name: "Akademi Farmasi Bumi Siliwangi",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 10161,
		name: "Universitas Aisyiyah Surakarta (AISKA University)",
		city: "Kota Surakarta",
		province: "Jawa Tengah",
	},
	{
		code: 10160,
		name: "Universitas Baiturrahmah",
		city: "Kota Padang",
		province: "Sumatera Barat",
	},
	{
		code: 10159,
		name: "Universitas Malahayati, Bandar Lampung",
		city: "Kota Bandar Lampung",
		province: "Lampung",
	},
	{
		code: 10158,
		name: "STAI Sebelas April Sumedang",
		city: "Kab. Sumedang",
		province: "Jawa Barat",
	},
	{
		code: 10157,
		name: "Universitas Islam As-Syafiiyah",
		city: "Kota Bekasi",
		province: "D.K.I. Jakarta",
	},
	{
		code: 10156,
		name: "Sekolah Tinggi Ilmu Syariah Al Wafa Bogor",
		city: "Kota Bogor",
		province: "Jawa Barat",
	},
	{
		code: 10155,
		name: "Universitas Dharma Andalas",
		city: "Kota Padang",
		province: "Sumatera Barat",
	},
	{
		code: 10154,
		name: "Universitas Internasional Semen Indonesia (UISI)",
		city: "Kab. Gresik",
		province: "Jawa Timur",
	},
	{
		code: 10153,
		name: "Universitas Muhammadiyah Sorong",
		city: "Kota Sorong",
		province: "Papua Barat",
	},
	{
		code: 10152,
		name: "Sekolah Tinggi Perikanan Dan Kelautan Matauli",
		city: "Kab. Tapanuli Tengah",
		province: "Sumatera Utara",
	},
	{
		code: 10151,
		name: "Universitas Yarsi, Jakarta",
		city: "Kota Jakarta Pusat",
		province: "D.K.I. Jakarta",
	},
	{
		code: 10150,
		name: "STAI Masjid Syuhada Yogyakarta",
		city: "Kota Yogyakarta",
		province: "D.I. Yogyakarta",
	},
	{
		code: 10149,
		name: "Universitas Balikpapan",
		city: "Kota Balikpapan",
		province: "Kalimantan Timur",
	},
	{
		code: 10148,
		name: "Sekolah Tinggi Ilmu Ushuluddin Darul Hikmah",
		city: "Kota Bekasi",
		province: "Jawa Barat",
	},
	{
		code: 10147,
		name: "Akademi Televisi Indonesia",
		city: "Kota Jakarta Barat",
		province: "D.K.I. Jakarta",
	},
	{
		code: 10146,
		name: "SMA (P3RI)",
		city: "-",
		province: "-",
	},
	{
		code: 10145,
		name: "STMIK Widya Utama",
		city: "Kab. Banyumas",
		province: "Jawa Tengah",
	},
	{
		code: 10144,
		name: "Universitas Catur Insan Cendekia Cirebon",
		city: "Kota Cirebon",
		province: "Jawa Barat",
	},
	{
		code: 10143,
		name: "STMIK Dipanegara",
		city: "Kota Makassar",
		province: "Sulawesi Selatan",
	},
	{
		code: 10142,
		name: "Institut Sains dan Teknologi Nasional Jakarta (ISTN Jakarta)",
		city: "Kota Jakarta Selatan",
		province: "D.K.I. Jakarta",
	},
	{
		code: 10141,
		name: "Politeknik Enjiniring Pertanian Indonesia",
		city: "Kota Tangerang",
		province: "Banten",
	},
	{
		code: 10140,
		name: "Sekolah Tinggi Ilmu Komputer Poltek Cirebon",
		city: "Kab. Cirebon",
		province: "Jawa Barat",
	},
	{
		code: 10139,
		name: "Institut Teknologi Tangerang Selatan",
		city: "Kota Tangerang Selatan",
		province: "Banten",
	},
	{
		code: 10138,
		name: "Sekolah Tinggi Teknologi Garut",
		city: "Kab. Garut",
		province: "Jawa Barat",
	},
	{
		code: 10137,
		name: "Universitas Ma'soem",
		city: "Kab. Sumedang",
		province: "Jawa Barat",
	},
	{
		code: 10136,
		name: "Universitas Indo Global Mandiri",
		city: "Kota Palembang",
		province: "Sumatera Selatan",
	},
	{
		code: 10135,
		name: "Universitas Prasetiya Mulya",
		city: "Kota Jakarta Selatan",
		province: "D.K.I. Jakarta",
	},
	{
		code: 10134,
		name: "STMIK AKAKOM Yogyakarta",
		city: "Kab. Bantul",
		province: "D.I. Yogyakarta",
	},
	{
		code: 10133,
		name: "Universitas Pamulang",
		city: "Kota Tangerang",
		province: "Banten",
	},
	{
		code: 10132,
		name: "Universitas Mercu Buana Yogyakarta",
		city: "Kab. Bantul",
		province: "D.I. Yogyakarta",
	},
	{
		code: 10131,
		name: "Universitas Islam Kalimantan Muhammad Arsyad Al Banjari",
		city: "Kota Banjarmasin",
		province: "Kalimantan Selatan",
	},
	{
		code: 10130,
		name: "Sekolah Tinggi Dirasat Islamiyah Imam Syafi'i Jember (STDIIS)",
		city: "Kab. Jember",
		province: "Jawa Timur",
	},
	{
		code: 10129,
		name: "Institut Bisnis & informatika Kosgoro 1957",
		city: "Kota Jakarta Selatan",
		province: "D.K.I. Jakarta",
	},
	{
		code: 10128,
		name: "Institut Teknologi Batam",
		city: "Kota Batam",
		province: "Kepulauan Riau",
	},
	{
		code: 10127,
		name: "IKIP Veteran Semarang ( Universitas IVET Semarang)",
		city: "Kota Semarang",
		province: "Jawa Tengah",
	},
	{
		code: 10126,
		name: "Universitas Mulia Balikpapan",
		city: "Kota Balikpapan",
		province: "Kalimantan Timur",
	},
	{
		code: 10125,
		name: "Universitas Pakuan Bogor",
		city: "Kota Bogor",
		province: "Jawa Barat",
	},
	{
		code: 10124,
		name: "Institut Teknologi dan Bisnis Bank Rakyat Indonesia (BRI Institute)",
		city: "Kota Jakarta Selatan",
		province: "D.K.I. Jakarta",
	},
	{
		code: 10123,
		name: "Universitas Muhammadiyah Lampung",
		city: "Kota Bandar Lampung",
		province: "Lampung",
	},
	{
		code: 10122,
		name: "STIMIK ESQ (ESQ Business School)",
		city: "Kota Jakarta Selatan",
		province: "D.K.I. Jakarta",
	},
	{
		code: 10121,
		name: "Universitas Pekalongan",
		city: "Kota Pekalongan",
		province: "Jawa Tengah",
	},
	{
		code: 10120,
		name: "Universitas Tarumanagara",
		city: "Kota Jakarta Barat",
		province: "D.K.I. Jakarta",
	},
	{
		code: 10119,
		name: "STIT At-Taqwa KPAD Gegerkalong",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 10118,
		name: "risakti School of Management ( STIE Trisakti)",
		city: "Kota Jakarta Barat",
		province: "D.K.I. Jakarta",
	},
	{
		code: 10117,
		name: "Universitas Peradaban",
		city: "Kab. Brebes",
		province: "Jawa Tengah",
	},
	{
		code: 10116,
		name: "Universitas Sahid Jakarta",
		city: "Kota Jakarta Selatan",
		province: "D.K.I. Jakarta",
	},
	{
		code: 10115,
		name: "STIE Pembangunan Tanjungpinang",
		city: "Kota Tanjungpinang",
		province: "Kepulauan Riau",
	},
	{
		code: 10114,
		name: "STIE Putra Bangsa Kebumen",
		city: "Kab. Kebumen",
		province: "Jawa Tengah",
	},
	{
		code: 10113,
		name: "Institut Teknologi Kalimantan",
		city: "Kota Balikpapan",
		province: "Kalimantan Timur",
	},
	{
		code: 10112,
		name: "Sekolah Tinggi Analis Kimia Cilegon",
		city: "Kota Cilegon",
		province: "Banten",
	},
	{
		code: 10111,
		name: "Politeknik Manufaktur Astra",
		city: "Kota Jakarta Utara",
		province: "D.K.I. Jakarta",
	},
	{
		code: 10110,
		name: "Politeknik Kesehatan Mataram",
		city: "Kota Mataram",
		province: "Nusa Tenggara Barat",
	},
	{
		code: 10109,
		name: "Institut Agama Islam Bakti Negara Tegal",
		city: "Kab. Tegal",
		province: "Jawa Tengah",
	},
	{
		code: 10108,
		name: "Institut Daarul Qur'an (IDAQU)",
		city: "Kota Tangerang",
		province: "Banten",
	},
	{
		code: 10107,
		name: "Poltekkes Kemenkes Riau",
		city: "Kota Pekanbaru",
		province: "Riau",
	},
	{
		code: 10106,
		name: "Sekolah Tinggi Bahasa Asing Yapari (STBA Yapari-ABA)",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 10105,
		name: "Universitas Sanata Dharma",
		city: "Kab. Sleman",
		province: "D.I. Yogyakarta",
	},
	{
		code: 10104,
		name: "STIKES Budi Luhur Cimahi",
		city: "Kota Cimahi",
		province: "Jawa Barat",
	},
	{
		code: 10103,
		name: "Politeknik Kesehatan TNI AU Ciumbuleuit",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 10102,
		name: "Sekolah Tinggi Islam Al-Mukmin Surakarta (STIM Surakarta)",
		city: "Kab. Sukoharjo",
		province: "Jawa Tengah",
	},
	{
		code: 10101,
		name: "Akademi Perekam Medis dan Informasi Kesehatan Bandung (APIKES BANDUNG)",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 10100,
		name: "Universitas Muhammadiyah Sidoarjo",
		city: "Kab. Sidoarjo",
		province: "Jawa Timur",
	},
	{
		code: 10099,
		name: "Universitas PGRI Semarang (UPGRIS)",
		city: "Kota Semarang",
		province: "Jawa Tengah",
	},
	{
		code: 10098,
		name: "Sekolah Tinggi Kesehatan Indonesia (STKINDO) Wirautama",
		city: "Kab. Bandung",
		province: "Jawa Barat",
	},
	{
		code: 10097,
		name: "Institut Teknologi Telkom Purwokerto",
		city: "Kab. Banyumas",
		province: "Jawa Tengah",
	},
	{
		code: 10096,
		name: "Universitas Bina Insani, Bekasi",
		city: "Kota Bekasi",
		province: "Jawa Barat",
	},
	{
		code: 10095,
		name: "Igdir University",
		city: "-",
		province: "-",
	},
	{
		code: 10094,
		name: "Politeknik Energi dan Pertambangan (PEP) Bandung",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 10093,
		name: "Sekolah Tinggi Manajemen Informatika dan Komputer (STMIK), Tasikmalaya",
		city: "Kota Tasikmalaya",
		province: "Jawa Barat",
	},
	{
		code: 10092,
		name: "Sekolah Tinggi Teknologi (STT) Mandala, Bandung",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 10091,
		name: "ITB SC (khusus pendaftar yang mengikuti jalur ITB SC, bukan SSC)",
		city: "-",
		province: "-",
	},
	{
		code: 10090,
		name: "Universitas Abulyatama, Aceh",
		city: "Kab. Aceh Besar",
		province: "Aceh",
	},
	{
		code: 10089,
		name: "Universitas Muhammadiyah Riau",
		city: "Kota Pekanbaru",
		province: "Riau",
	},
	{
		code: 10088,
		name: "Universitas Veteran Bangun Nusantara, Sukoharjo",
		city: "Kab. Sukoharjo",
		province: "Jawa Tengah",
	},
	{
		code: 10087,
		name: "Sekolah Tinggi Ilmu Kesehatan (STIKes) Garut",
		city: "Kab. Garut",
		province: "Jawa Barat",
	},
	{
		code: 10086,
		name: "Universitas Langlangbuana, Bandung",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 10085,
		name: "Universitas Muhammadiyah Sukabumi, Sukabumi",
		city: "Kota Sukabumi",
		province: "Jawa Barat",
	},
	{
		code: 10084,
		name: "Sekolah Tinggi Ilmu Ushuluddin Dirosat Islamiyah Al-Hikmah, Jakarta",
		city: "Kota Jakarta Selatan",
		province: "D.K.I. Jakarta",
	},
	{
		code: 10083,
		name: "Sekolah Tinggi Manajemen Asuransi Trisakti, Jakarta",
		city: "Kota Jakarta Timur",
		province: "D.K.I. Jakarta",
	},
	{
		code: 10082,
		name: "Institut Sains & Teknologi AKPRIND, Yogyakarta",
		city: "Kota Yogyakarta",
		province: "D.I. Yogyakarta",
	},
	{
		code: 10081,
		name: "Institut STIAMI",
		city: "Kota Tangerang Selatan",
		province: "Banten",
	},
	{
		code: 10080,
		name: "Universitas Amikom, Yogyakarta",
		city: "Kab. Sleman",
		province: "D.I. Yogyakarta",
	},
	{
		code: 10079,
		name: "Akademi Fisioterapi Rumah Sakit Dustira",
		city: "Kota Cimahi",
		province: "Jawa Barat",
	},
	{
		code: 10078,
		name: "Universitas Islam Malang, Malang",
		city: "Kota Malang",
		province: "Jawa Timur",
	},
	{
		code: 10077,
		name: "Sekolah Tinggi Ilmu Ekonomi (STIE) Gema Widya Bangsa",
		city: "Kab. Bandung",
		province: "Jawa Barat",
	},
	{
		code: 10076,
		name: "Changzhou Institute of Industry Technology",
		city: "-",
		province: "-",
	},
	{
		code: 10075,
		name: "Universitas Abdurrab (Univrab), Pekanbaru",
		city: "Kota Pekanbaru",
		province: "Riau",
	},
	{
		code: 10074,
		name: "AMIK Tunas Bangsa, Pematangsiantar",
		city: "Kota Pematangsiantar",
		province: "Sumatera Utara",
	},
	{
		code: 10073,
		name: "Changzhou College of Information Technology",
		city: "-",
		province: "-",
	},
	{
		code: 10072,
		name: "Universitas Satyagama",
		city: "Kota Jakarta Barat",
		province: "D.K.I. Jakarta",
	},
	{
		code: 10071,
		name: "Institut Islam Mamba'ul Ulum, Surakarta",
		city: "Kota Surakarta",
		province: "Jawa Tengah",
	},
	{
		code: 10070,
		name: "Institut Agama Islam Yasni, Bungo",
		city: "Kab. Bungo",
		province: "Jambi",
	},
	{
		code: 10069,
		name: "Universitas Widya Mataram, Yogyakarta",
		city: "Kota Yogyakarta",
		province: "D.I. Yogyakarta",
	},
	{
		code: 10068,
		name: "Universitas Islam Syekh-Yusuf (UNIS), Tangerang",
		city: "Kota Tangerang",
		province: "Banten",
	},
	{
		code: 10067,
		name: "Akademi Manajemen Informatika dan Komputer (AMIK) HASS, Bandung",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 10066,
		name: "Sekolah Tinggi Keguruan dan Ilmu Pendidikan (STKIP) Bina Mutiara, Sukabumi",
		city: "Kota Sukabumi",
		province: "Jawa Barat",
	},
	{
		code: 10065,
		name: "Institut Ilmu Kesehatan (IIK) Bhakti Wiyata, Kediri",
		city: "Kota Kediri",
		province: "Jawa Timur",
	},
	{
		code: 10064,
		name: "Universitas Subang",
		city: "Kab. Subang",
		province: "Jawa Barat",
	},
	{
		code: 10063,
		name: "Universitas pembangunan jaya, Tanggerang Selatan",
		city: "Kota Tangerang Selatan",
		province: "Banten",
	},
	{
		code: 10062,
		name: "Universitas Wiralodra, Indramayu",
		city: "Kab. Indramayu",
		province: "Jawa Barat",
	},
	{
		code: 10061,
		name: "Institut Agama Islam Darussalam (IAID), Ciamis",
		city: "Kab. Ciamis",
		province: "Jawa Barat",
	},
	{
		code: 10060,
		name: "Sekolah Tinggi Ilmu Tarbiyah (STIT) Al-Hidayah, Tasikmalaya",
		city: "Kota Tasikmalaya",
		province: "Jawa Barat",
	},
	{
		code: 10059,
		name: "Sekolah Tinggi Agama Islam Syekh Manshur (STAISMAN)",
		city: "Kab. Pandeglang",
		province: "Banten",
	},
	{
		code: 10058,
		name: "Sekolah Tinggi Pariwisata Bandung",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 10057,
		name: "Universitas Muslim Indonesia",
		city: "Kota Makassar",
		province: "Sulawesi Selatan",
	},
	{
		code: 10056,
		name: "President University",
		city: "Kab. Bekasi",
		province: "Jawa Barat",
	},
	{
		code: 10055,
		name: "Politeknik Bisnis dan Pasar Modal (BCM School), Jakarta",
		city: "Kota Jakarta Selatan",
		province: "D.K.I. Jakarta",
	},
	{
		code: 10054,
		name: "Sekolah Tinggi Agama Islam Negeri (STAIN) Sultan Abdurrahman Kepulauan Riau (KEPRI)",
		city: "Kab. Bintan",
		province: "Kepulauan Riau",
	},
	{
		code: 10053,
		name: "Sekolah Tinggi Ilmu Ekonomi (STIE) Yasa Anggana, Garut",
		city: "Kab. Garut",
		province: "Jawa Barat",
	},
	{
		code: 10052,
		name: "STMIK Triguna Dharma",
		city: "Kota Medan",
		province: "Sumatera Utara",
	},
	{
		code: 10051,
		name: "Sekolah Tinggi Agama Islam Pengembangan Ilmu Al Quran (STAIPIQ), Padang",
		city: "Kota Padang",
		province: "Sumatera Barat",
	},
	{
		code: 10050,
		name: "Universitas Surabaya (UBAYA)",
		city: "Kota Surabaya",
		province: "Jawa Timur",
	},
	{
		code: 10049,
		name: "Sekolah Tinggi Agama Islam (STAI) Asy-Syukriyyah, Tangerang",
		city: "Kota Tangerang",
		province: "Banten",
	},
	{
		code: 10048,
		name: "Universitas PGRI Madiun",
		city: "Kota Madiun",
		province: "Jawa Timur",
	},
	{
		code: 10047,
		name: "Kalla Business School",
		city: "Kota Makassar",
		province: "Sulawesi Selatan",
	},
	{
		code: 10046,
		name: "Universitas Muhammadiyah Ponorogo",
		city: "Kab. Ponorogo",
		province: "Jawa Timur",
	},
	{
		code: 10045,
		name: "Institut Agama Islam Negeri (IAIN) Bukittinggi",
		city: "Kota Bukittinggi",
		province: "Sumatera Barat",
	},
	{
		code: 10044,
		name: "Sekolah Tinggi Agama Islam Al-Musaddadiyah (STAIM), Garut",
		city: "Kab. Garut",
		province: "Jawa Barat",
	},
	{
		code: 10043,
		name: "LIPIA Jakarta",
		city: "Kota Jakarta Selatan",
		province: "D.K.I. Jakarta",
	},
	{
		code: 10042,
		name: "Politeknik Kesehatan Kemenkes (Poltekkes) Jambi",
		city: "Kota Jambi",
		province: "Jambi",
	},
	{
		code: 10041,
		name: "Sekolah Tinggi Agama Islam Persatuan Islam (STAIPI), Bandung",
		city: "Kab. Bandung",
		province: "Jawa Barat",
	},
	{
		code: 10040,
		name: "Institut Ilmu Sosial dan Ilmu Politik (IISIP), Jakarta",
		city: "Kota Jakarta Selatan",
		province: "D.K.I. Jakarta",
	},
	{
		code: 10039,
		name: "Sekolah Tinggi Ilmu Pertanian Agrobisnis Perkebunan (STIPAP), Medan",
		city: "Kota Medan",
		province: "Sumatera Utara",
	},
	{
		code: 10038,
		name: "Universitas Nahdlatul Ulama Indonesia (UNUSIA)",
		city: "Kota Jakarta Pusat",
		province: "D.K.I. Jakarta",
	},
	{
		code: 10037,
		name: "Universitas Muhammadiyah Malang",
		city: "Kota Malang",
		province: "Jawa Timur",
	},
	{
		code: 10036,
		name: "Sekolah Tinggi Manajemen Informatika dan Komputer (STMIK) IKMI Cirebon",
		city: "Kota Cirebon",
		province: "Jawa Barat",
	},
	{
		code: 10035,
		name: "Lembaga Pendidikan dan Pengembangan Profesi Indonesia (LP3I), Tasikmalaya",
		city: "Kota Tasikmalaya",
		province: "Jawa Barat",
	},
	{
		code: 10034,
		name: "Sekolah Tinggi Keguruan dan Ilmu Pendidikan (STKIP) Muhammadiyah Kuningan",
		city: "Kab. Kuningan",
		province: "Jawa Barat",
	},
	{
		code: 10033,
		name: "Universitas Persatuan Islam (UNIPI)",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 10032,
		name: "Sekolah Tinggi Agama Islam ( STAI) Sabili",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 10031,
		name: "Universitas Bale Bandung (UNIBBA)",
		city: "Kab. Bandung",
		province: "Jawa Barat",
	},
	{
		code: 10030,
		name: "Sekolah Tinggi Keguruan Ilmu Pendidikan (STKIP) Adzkia",
		city: "Kota Padang",
		province: "Sumatera Barat",
	},
	{
		code: 10029,
		name: "Universitas Muhammadiyah Prof. Dr. Hamka (UHAMKA)",
		city: "Kota Jakarta Selatan",
		province: "D.K.I. Jakarta",
	},
	{
		code: 10027,
		name: "Universitas Muhammadiyah Tasikmalaya (UMTAS)",
		city: "Kota Tasikmalaya",
		province: "Jawa Barat",
	},
	{
		code: 10026,
		name: "LIPIA Surabaya",
		city: "Kota Surabaya",
		province: "Jawa Timur",
	},
	{
		code: 10025,
		name: "STIKES Mambaul Ulum, Surakarta",
		city: "Kota Surakarta",
		province: "Jawa Tengah",
	},
	{
		code: 10024,
		name: "Universitas Muria Kudus",
		city: "Kab. Kudus",
		province: "Jawa Tengah",
	},
	{
		code: 10023,
		name: "Sekolah Tinggi Manajemen Informatika dan Komputer (STMIK) DCI, Tasikmalaya",
		city: "Kota Tasikmalaya",
		province: "Jawa Barat",
	},
	{
		code: 10022,
		name: "Universitas Semarang",
		city: "Kota Semarang",
		province: "Jawa Tengah",
	},
	{
		code: 10021,
		name: "Universitas Muhammadiyah Surabaya",
		city: "Kota Surabaya",
		province: "Jawa Timur",
	},
	{
		code: 10020,
		name: "STIS Husnul Khotimah, Kuningan",
		city: "Kab. Kuningan",
		province: "Jawa Barat",
	},
	{
		code: 10019,
		name: "Universitas Islam Riau",
		city: "Kota Pekanbaru",
		province: "Riau",
	},
	{
		code: 10018,
		name: "Sakarya university",
		city: "-",
		province: "-",
	},
	{
		code: 10017,
		name: "Sekolah Tinggi Ekonomi Islam (STEI) Hamfara",
		city: "Kab. Bantul",
		province: "D.I. Yogyakarta",
	},
	{
		code: 10016,
		name: "STMIK Antar Bangsa Daarul Qur'an, Tangerang",
		city: "Kota Tangerang",
		province: "Banten",
	},
	{
		code: 10015,
		name: "Universitas Muhammadiyah Gresik",
		city: "Kab. Gresik",
		province: "Jawa Timur",
	},
	{
		code: 10014,
		name: "STIT Hidayatullah Batam",
		city: "Kota Batam",
		province: "Kepulauan Riau",
	},
	{
		code: 10013,
		name: "Albukhary International University",
		city: "-",
		province: "-",
	},
	{
		code: 10012,
		name: "Universitas Pancasila",
		city: "Kota Jakarta Selatan",
		province: "D.K.I. Jakarta",
	},
	{
		code: 10011,
		name: "Sekolah Tinggi Farmasi Indonesia",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 10010,
		name: "STIE Kridatama",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 10009,
		name: "Universitas Islam Sultan Agung, Semarang",
		city: "Kota Semarang",
		province: "Jawa Tengah",
	},
	{
		code: 10008,
		name: "STT Terpadu Nurul Fikri, Jakarta",
		city: "Kota Jakarta Selatan",
		province: "D.K.I. Jakarta",
	},
	{
		code: 10006,
		name: "STAI Siliwangi Bandung, Bandung",
		city: "Kota Cimahi",
		province: "Jawa Barat",
	},
	{
		code: 10005,
		name: "Universitas Djuanda Bogor, Bogor",
		city: "Kab. Bogor",
		province: "Jawa Barat",
	},
	{
		code: 10004,
		name: "Universitas Kuningan (UNIKU)",
		city: "Kab. Kuningan",
		province: "Jawa Barat",
	},
	{
		code: 450,
		name: "Universitas Islam Al Ihya Kuningan",
		city: "Kab. Kuningan",
		province: "Jawa Barat",
	},
	{
		code: 449,
		name: "Universitas Aisyiyah Yogyakarta (UNISA)",
		city: "Kab. Sleman",
		province: "D.I. Yogyakarta",
	},
	{
		code: 448,
		name: "Politeknik API Yogyakarta",
		city: "Kab. Sleman",
		province: "D.I. Yogyakarta",
	},
	{
		code: 447,
		name: "Politeknik Gajah Tunggal",
		city: "Kota Tangerang",
		province: "Banten",
	},
	{
		code: 446,
		name: "Politeknik TEDC Bandung",
		city: "Kota Cimahi",
		province: "Jawa Barat",
	},
	{
		code: 445,
		name: "Sekolah Tinggi Agama Islam Yapata Al Jawami",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 444,
		name: "Sekolah Tinggi Ilmu Dakwah Dirosat Islamiyyah Al-Hikmah",
		city: "Kota Jakarta Selatan",
		province: "D.K.I. Jakarta",
	},
	{
		code: 443,
		name: "STKIP Sebelas April Sumedang",
		city: "Kab. Sumedang",
		province: "Jawa Barat",
	},
	{
		code: 442,
		name: "Sekolah Tinggi Meteorologi Klimatologi dan Geofisika",
		city: "Kota Tangerang Selatan",
		province: "Banten",
	},
	{
		code: 441,
		name: "Politeknik Kesehatan Kementrian Kesehatan Yogyakarta",
		city: "Kab. Sleman",
		province: "D.I. Yogyakarta",
	},
	{
		code: 440,
		name: "Poltekkes Kemenkes Jakarta 2",
		city: "Kota Jakarta Selatan",
		province: "D.K.I. Jakarta",
	},
	{
		code: 439,
		name: "STAI Riyadhul Jannah Subang",
		city: "Kab. Subang",
		province: "Jawa Barat",
	},
	{
		code: 438,
		name: "STIKES Jenderal Achmad Yani Cimahi",
		city: "Kota Cimahi",
		province: "Jawa Barat",
	},
	{
		code: 437,
		name: "Universitas Ibnu Chaldun",
		city: "Kota Jakarta Timur",
		province: "D.K.I. Jakarta",
	},
	{
		code: 436,
		name: "Universitas Parahyangan",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 435,
		name: "Universitas Perjuangan",
		city: "Kota Tasikmalaya",
		province: "Jawa Barat",
	},
	{
		code: 434,
		name: "Universitas Winaya Mukti",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 433,
		name: "Akademi Keperawatan Cianjur",
		city: "Kab. Cianjur",
		province: "Jawa Barat",
	},
	{
		code: 432,
		name: "IPU",
		city: "-",
		province: "-",
	},
	{
		code: 431,
		name: "STFi",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 430,
		name: "Institut Teknologi Nasional, Malang",
		city: "Kota Malang",
		province: "Jawa Timur",
	},
	{
		code: 429,
		name: "Akademi Pariwisata NHI Bandung",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 428,
		name: "Akademi Sekretaris dan Manajemen Taruna Bakti",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 427,
		name: "Akademi teknologi pulp dan kertas",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 426,
		name: "Indonesia banking school",
		city: "Kota Jakarta Selatan",
		province: "D.K.I. Jakarta",
	},
	{
		code: 425,
		name: "Institut Agama Islam Cipasung (IAIC) Tasikmalaya",
		city: "Kab. Tasikmalaya",
		province: "Jawa Barat",
	},
	{
		code: 424,
		name: "Institut Ilmu Al-Quran Jakarta",
		city: "Kota Tangerang Selatan",
		province: "Banten",
	},
	{
		code: 423,
		name: "Institut Perguruan Tinggi Ilmu al-Quran Jakarta (IPTIQ Jakarta)",
		city: "Kota Jakarta Selatan",
		province: "D.K.I. Jakarta",
	},
	{
		code: 422,
		name: "Institut Tazkia",
		city: "Kota Bogor",
		province: "Jawa Barat",
	},
	{
		code: 421,
		name: "Lembaga Pendidikan dan Pengembangan Profesi Indonesia (LP3I), Bandung",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 420,
		name: "Politeknik AKA Bogor",
		city: "Kota Bogor",
		province: "Jawa Barat",
	},
	{
		code: 419,
		name: "Politeknik Al Islam Bandung",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 418,
		name: "Politeknik Kesehatan Kemenkes (Poltekkes) Tasikmalaya",
		city: "Kab. Tasikmalaya",
		province: "Jawa Barat",
	},
	{
		code: 417,
		name: "Politeknik Kesehatan Padang",
		city: "Kota Padang",
		province: "Sumatera Barat",
	},
	{
		code: 416,
		name: "Politeknik Kesejahteraan Sosial (Poltekesos) Bandung",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 415,
		name: "Politeknik LPKIA Bandung",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 414,
		name: "Politeknik Manufaktur Negeri Bangka Belitung",
		city: "Kab. Bangka",
		province: "Kepulauan Bangka Belitung",
	},
	{
		code: 413,
		name: "Politeknik Pajajaran",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 412,
		name: "Politeknik Praktisi Bandung",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 411,
		name: "Politeknik Sekolah Tinggi Manajemen Industri Jakarta",
		city: "Kota Jakarta Pusat",
		province: "D.K.I. Jakarta",
	},
	{
		code: 410,
		name: "Sekolah Tinggi Ekonomi Islam (STEI) SEBI",
		city: "Kota Depok",
		province: "Jawa Barat",
	},
	{
		code: 409,
		name: "Sekolah Tinggi Farmasi Bandung",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 408,
		name: "Sekolah tinggi hukum bandung",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 407,
		name: "Sekolah Tinggi Ilmu Al-Qur'an Al-Multazam",
		city: "Kab. Kuningan",
		province: "Jawa Barat",
	},
	{
		code: 406,
		name: "Sekolah Tinggi Ilmu Kesehatan Surya Global",
		city: "Kota Bantul",
		province: "D.I. Yogyakarta",
	},
	{
		code: 405,
		name: "Sekolah Tinggi Ilmu Manajemen YKPN",
		city: "Kab. Sleman",
		province: "D.I. Yogyakarta",
	},
	{
		code: 404,
		name: "Sekolah Tinggi Seni Rupa dan Desain Indonesia Telkom",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 403,
		name: "Sekolah Tinggi Teknik Yayasan Bhakti Sosrohadisewojo Internasional",
		city: "Kota Tasikmalaya",
		province: "Jawa Barat",
	},
	{
		code: 402,
		name: "STAI Tasikmalaya",
		city: "Kota Tasikmalaya",
		province: "Jawa Barat",
	},
	{
		code: 401,
		name: "STAI Persis Bandung",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 400,
		name: "STAI Persis Garut",
		city: "Kab. Garut",
		province: "Jawa Barat",
	},
	{
		code: 399,
		name: "Sekolah Tinggi Sains dan Teknologi Indonesia",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 398,
		name: "Sekolah Tinggi Teknologi Bandung",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 397,
		name: "STAI Yamisa",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 396,
		name: "STEMBI Bandung Business School",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 395,
		name: "STIA LAN Bandung",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 394,
		name: "STID DI Al-Hikmah Jakarta",
		city: "Kota Jakarta Selatan",
		province: "D.K.I. Jakarta",
	},
	{
		code: 393,
		name: "STID MUH. NATSIR",
		city: "Kota Jakarta Timur",
		province: "D.K.I. Jakarta",
	},
	{
		code: 392,
		name: "STIE Binaniaga Bogor",
		city: "Kota Bogor",
		province: "Jawa Barat",
	},
	{
		code: 391,
		name: "STIE Inaba",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 390,
		name: "STIES Darul Ulum Purwakarta",
		city: "Kab. Purwakarta",
		province: "Jawa Barat",
	},
	{
		code: 389,
		name: "STIKES Surya Global Yogyakarta",
		city: "Kota Bantul",
		province: "D.I. Yogyakarta",
	},
	{
		code: 388,
		name: "STKIP Pasundan",
		city: "Kota Cimahi",
		province: "Jawa Barat",
	},
	{
		code: 387,
		name: "STMIK BANDUNG",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 386,
		name: "Universitas Ibnu Sina Batam",
		city: "Kota Batam",
		province: "Kepulauan Riau",
	},
	{
		code: 385,
		name: "STIE Tridharma Bandung",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 384,
		name: "Univeristas Nasional Pasim",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 383,
		name: "Universitas Ahmad Dahlan Yogyakarta",
		city: "Kota Yogyakarta",
		province: "D.I. Yogyakarta",
	},
	{
		code: 382,
		name: "Universitas Al Azhar Indonesia",
		city: "Kota Jakarta Selatan",
		province: "D.K.I. Jakarta",
	},
	{
		code: 381,
		name: "Universitas Al-Ghifari (UNFARI)",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 380,
		name: "Universitas Bakrie",
		city: "Kota Kuningan",
		province: "D.K.I. Jakarta",
	},
	{
		code: 379,
		name: "Universitas Bhakti Kencana Bandung",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 378,
		name: "Universitas Bosowa",
		city: "Kota Makassar",
		province: "Sulawesi Selatan",
	},
	{
		code: 377,
		name: "Universitas Galuh Ciamis",
		city: "Kab. Ciamis",
		province: "Jawa Barat",
	},
	{
		code: 376,
		name: "Politeknik Negeri Media Kreatif Jakarta",
		city: "Kota Jakarta Selatan",
		province: "D.K.I. Jakarta",
	},
	{
		code: 375,
		name: "Sekolah Tinggi Ilmu Keperawatan PPNI Jawa Barat",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 374,
		name: "Tanri Abeng University",
		city: "Kota Jakarta Selatan",
		province: "D.K.I. Jakarta",
	},
	{
		code: 373,
		name: "Universitas Halim Sanusi PUI Bandung",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 372,
		name: "Universitas Halu Oleo",
		city: "Kota Kendari",
		province: "Sulawesi Tenggara",
	},
	{
		code: 371,
		name: "Universitas Informatika dan Bisnis Indonesia",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 370,
		name: "Universitas Islam '45' Bekasi",
		city: "Kota Bekasi",
		province: "Jawa Barat",
	},
	{
		code: 369,
		name: "Universitas Kebangsaan Republik Indonesia",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 368,
		name: "Universitas Pembangunan Panca Budi Medan",
		city: "Kota Medan",
		province: "Sumatera Utara",
	},
	{
		code: 367,
		name: "Universitas Pesantren Tinggi Darul Ulum Jombang",
		city: "Kab. Jombang",
		province: "Jawa Timur",
	},
	{
		code: 366,
		name: "Universitas Proklamasi 45 Yogyakarta",
		city: "Kab. Sleman",
		province: "D.I. Yogyakarta",
	},
	{
		code: 365,
		name: "Sekolah Tinggi Keguruan dan Ilmu Pendidikan (STKIP) Al Hikmah Surabaya",
		city: "Kota Surabaya",
		province: "Jawa Timur",
	},
	{
		code: 364,
		name: "Universitas Bina Nusantara",
		city: "Kota Jakarta Barat",
		province: "D.K.I. Jakarta",
	},
	{
		code: 363,
		name: "Universitas Garut",
		city: "Kab. Garut",
		province: "Jawa Barat",
	},
	{
		code: 362,
		name: "Universitas Maranatha",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 361,
		name: "Universitas Pembangunan Nasional Veteran (UPN), Jakarta",
		city: "Kota Jakarta Selatan",
		province: "D.K.I. Jakarta",
	},
	{
		code: 360,
		name: "Universitas Bina Sarana Informatika",
		city: "Kota Jakarta Barat",
		province: "D.K.I. Jakarta",
	},
	{
		code: 359,
		name: "Institut Pendidikan Indonesia",
		city: "Kab. Garut",
		province: "Jawa Barat",
	},
	{
		code: 358,
		name: "Institut Koperasi dan Manajemen Indonesia",
		city: "Kab. Sumedang",
		province: "Jawa Barat",
	},
	{
		code: 357,
		name: "Universitas 17 Agustus 1945 Cirebon",
		city: "Kota Cirebon",
		province: "Jawa Barat",
	},
	{
		code: 356,
		name: "Universitas Bandung Raya",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 355,
		name: "Universitas Dian Nuswantoro",
		city: "Kota Semarang",
		province: "Jawa Tengah",
	},
	{
		code: 354,
		name: "Universitas Lambung Mangkurat Banjarmasin",
		city: "Kota Banjarmasin",
		province: "Kalimantan Selatan",
	},
	{
		code: 353,
		name: "Universitas Paramadina",
		city: "Kota Jakarta Selatan",
		province: "D.K.I. Jakarta",
	},
	{
		code: 352,
		name: "Ma'had Al Imarat Bandung",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 351,
		name: "Politeknik Keuangan Negara STAN",
		city: "Kota tangerang Selatan",
		province: "Banten",
	},
	{
		code: 350,
		name: "Politeknik Pertanian Negeri Pangkep",
		city: "Kab. Pangkajene Kepulauan",
		province: "Sulawesi Selatan",
	},
	{
		code: 349,
		name: "Politeknik Piksi Ganesha Bandung",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 348,
		name: "Politeknik Pos Indonesia",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 347,
		name: "Politeknik Statistika STIS",
		city: "Kota Jakarta Timur",
		province: "D.K.I. Jakarta",
	},
	{
		code: 346,
		name: "Poltekkes Kemenkes Jakarta III",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 345,
		name: "STIE Ekuitas Bandung",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 344,
		name: "Universitas Internasional Batam",
		city: "Kota Batam",
		province: "Kepulauan Riau",
	},
	{
		code: 343,
		name: "Universitas Indraprasta PGRI",
		city: "Kota Jakarta Selatan",
		province: "D.K.I. Jakarta",
	},
	{
		code: 342,
		name: "Universitas Islam Negeri Sultan Maulana Hasanuddin banten",
		city: "Kota Serang",
		province: "Banten",
	},
	{
		code: 341,
		name: "Universitas Islam Nusantara (UNINUS)",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 340,
		name: "Universitas Muhammadiyah Bandung",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 339,
		name: "Universitas Muhammadiyah Cirebon",
		city: "Kab. Cirebon",
		province: "Jawa Barat",
	},
	{
		code: 338,
		name: "Universitas Muhammadiyah Jakarta",
		city: "Kota tangerang Selatan",
		province: "Banten",
	},
	{
		code: 337,
		name: "Universitas Muhammadiyah Jember",
		city: "Kab. Jember",
		province: "Jawa Timur",
	},
	{
		code: 336,
		name: "Universitas Muhammadiyah Purwokerto",
		city: "Kab. Banyumas",
		province: "Jawa Tengah",
	},
	{
		code: 335,
		name: "Universitas Muhammadiyah Surakarta",
		city: "Kab. Sukoharjo",
		province: "Jawa Tengah",
	},
	{
		code: 334,
		name: "Universitas Teknologi Sumbawa",
		city: "Kab. Sumbawa",
		province: "Nusa Tenggara Barat",
	},
	{
		code: 333,
		name: "Universitas Teknologi Yogyakarta",
		city: "Kab. Sleman",
		province: "D.I. Yogyakarta",
	},
	{
		code: 332,
		name: "Universitas Terbuka",
		city: "Kota Tangerang Selatan",
		province: "D.K.I. Jakarta",
	},
	{
		code: 331,
		name: "Universitas Trisakti",
		city: "Kota Jakarta Barat",
		province: "D.K.I. Jakarta",
	},
	{
		code: 330,
		name: "UNiversitas Trunojoyo Madura",
		city: "Kab. Bangkalan",
		province: "Jawa Timur",
	},
	{
		code: 329,
		name: "Politeknik Sekolah Tinggi Textil (STT) Bandung",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 328,
		name: "Universitas Darussalam Gontor",
		city: "Kab. Ponorogo",
		province: "Jawa Timur",
	},
	{
		code: 327,
		name: "Universitas Islam Indonesia",
		city: "Kab. Sleman",
		province: "D.I. Yogyakarta",
	},
	{
		code: 326,
		name: "Universitas Islam Negeri Sultan Maulana Hasanuddin Banten",
		city: "Kota Serang",
		province: "Banten",
	},
	{
		code: 325,
		name: "Universitas Komputer Indonesia",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 324,
		name: "Universitas Muhammadiyah Yogyakarta",
		city: "Kab. Bantul",
		province: "D.I. Yogyakarta",
	},
	{
		code: 323,
		name: "Sekolah Tinggi Ilmu Ekonomi Pasundan",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 322,
		name: "Universitas Jenderal Achmad Yani, Cimahi",
		city: "Kota Cimahi",
		province: "Jawa Barat",
	},
	{
		code: 321,
		name: "Universitas Nasional",
		city: "Kota Jakarta Selatan",
		province: "D.K.I. Jakarta",
	},
	{
		code: 320,
		name: "Universitas Nasional Pasim",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 319,
		name: "Universitas Pertamina",
		city: "Kota Jakarta Selatan",
		province: "D.K.I. Jakarta",
	},
	{
		code: 318,
		name: "Universitas Sangga Buana YPKP Bandung",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 317,
		name: "Universitas Widyatama",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 316,
		name: "Universitas Telkom",
		city: "Kab. Bandung",
		province: "Jawa Barat",
	},
	{
		code: 315,
		name: "Institut Teknologi Sumatera",
		city: "Kab. Lampung Selatan",
		province: "Lampung",
	},
	{
		code: 314,
		name: "Institut Teknologi Nasional, Bandung",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 313,
		name: "Institut Teknologi dan Sains Bandung",
		city: "Kab. Bekasi",
		province: "Jawa Barat",
	},
	{
		code: 312,
		name: "IKIP Siliwangi Bandung",
		city: "Kota Cimahi",
		province: "Jawa Barat",
	},
	{
		code: 311,
		name: "IAIN Syekh Nurjati Cirebon",
		city: "Kota Cirebon",
		province: "Jawa Barat",
	},
	{
		code: 310,
		name: "Akademi Metrologi dan Instrumentasi (AKMET)",
		city: "Kab. Sumedang",
		province: "Jawa Barat",
	},
	{
		code: 309,
		name: "Universitas Islam Bandung (UNISBA)",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 308,
		name: "Universitas Pasundan Bandung",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 307,
		name: "UIN Sunan Gunung Djati Bandung",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 306,
		name: "Sekolah Tinggi Penyuluhan Pertanian (STTP) Manokwari",
		city: "Kab. Manokwari",
		province: "Papua Barat",
	},
	{
		code: 305,
		name: "STAIN Sorong",
		city: "Kota Sorong",
		province: "Papua Barat",
	},
	{
		code: 304,
		name: "Universitas Negeri Papua, Manokwari",
		city: "Kab. Manokwari",
		province: "Papua Barat",
	},
	{
		code: 303,
		name: "Sekolah Tinggi. Agama Kristen Negeri (STAKN) Jayapura",
		city: "Kab. Jayapura",
		province: "Papua",
	},
	{
		code: 302,
		name: "STAIN Al-Fatah, Jayapura",
		city: "Kota Jayapura",
		province: "Papua",
	},
	{
		code: 301,
		name: "Universitas Musamus Merauke, Merauke",
		city: "Kab. Merauke",
		province: "Papua",
	},
	{
		code: 300,
		name: "Universitas Cendrawasih, Jayapura",
		city: "Kota Jayapura",
		province: "Papua",
	},
	{
		code: 299,
		name: "IAIN Ternate, Ternate",
		city: "Kota Ternate",
		province: "Maluku Utara",
	},
	{
		code: 298,
		name: "Universitas Khairun, Ternate",
		city: "Kota Ternate",
		province: "Maluku Utara",
	},
	{
		code: 297,
		name: "STAIN Ambon",
		city: "Kota Ambon",
		province: "Maluku",
	},
	{
		code: 296,
		name: "Sekolah Tinggi Agama Kristen Protestan Negeri Ambon",
		city: "Kota Ambon",
		province: "Maluku",
	},
	{
		code: 295,
		name: "IAIN Ambon",
		city: "Kota Ambon",
		province: "Maluku",
	},
	{
		code: 294,
		name: "STAKPN Ambon",
		city: "Kota Ambon",
		province: "Maluku",
	},
	{
		code: 293,
		name: "Politeknik Perikanan Negeri Tual, Tual",
		city: "Kab. Maluku Tenggara",
		province: "Maluku",
	},
	{
		code: 292,
		name: "Politeknik Negeri Ambon, Ambon",
		city: "Kota Ambon",
		province: "Maluku",
	},
	{
		code: 291,
		name: "Universitas Darussalam, Ambon",
		city: "Kota Ambon",
		province: "Maluku",
	},
	{
		code: 290,
		name: "Universitas Pattimura, Ambon",
		city: "Kota Ambon",
		province: "Maluku",
	},
	{
		code: 289,
		name: "Universitas Negeri Sulawesi Barat",
		city: "Kab. Majene",
		province: "Sulawesi Barat",
	},
	{
		code: 288,
		name: "IAIN Kendari, Palu",
		city: "Kota Palu",
		province: "Sulawesi Tengah",
	},
	{
		code: 287,
		name: "Universitas Sulawesi Tenggara",
		city: "Kota Kendari",
		province: "Sulawesi Tenggara",
	},
	{
		code: 286,
		name: "Universitas Muhammadiyah Buton",
		city: "Kota Baubau",
		province: "Sulawesi Tenggara",
	},
	{
		code: 285,
		name: "Universitas Dayanu Iksanudin",
		city: "Kota Baubau",
		province: "Sulawesi Tenggara",
	},
	{
		code: 284,
		name: "Universitas Lakidende",
		city: "Kab. Konawe",
		province: "Sulawesi Tenggara",
	},
	{
		code: 283,
		name: "Universitas Muhammadiyah Kendari",
		city: "Kota Kendari",
		province: "Sulawesi Tenggara",
	},
	{
		code: 282,
		name: "Universitas 19 November Kolaka",
		city: "Kab. Kolaka",
		province: "Sulawesi Tenggara",
	},
	{
		code: 281,
		name: "STAIN Kendari",
		city: "Kota Kendari",
		province: "Sulawesi Tenggara",
	},
	{
		code: 280,
		name: "Sekolah Tinggi Pertanian (STIP) Muna Kampus Baru, Muna",
		city: "Kab. Muna",
		province: "Sulawesi Tenggara",
	},
	{
		code: 279,
		name: "Universitas Haluoleo, Kendari",
		city: "Kota Kendari",
		province: "Sulawesi Tenggara",
	},
	{
		code: 278,
		name: "Akademi Teknik Keselamatan Penerbangan Makasar",
		city: "Kota Makassar",
		province: "Sulawesi Selatan",
	},
	{
		code: 277,
		name: "Sekolah Tinggi Penyuluhan Pertanian (STTP) Gowa",
		city: "Kab. Gowa",
		province: "Sulawesi Selatan",
	},
	{
		code: 276,
		name: "Sekolah Tinggi Agama Kristen Negeri (STAKN) Toraja",
		city: "Kab. Tana Toraja",
		province: "Sulawesi Selatan",
	},
	{
		code: 275,
		name: "Sekolah Tinggi Seni Indonesia, Padang Panjang",
		city: "Kota Padangpanjang",
		province: "Sumatera Barat",
	},
	{
		code: 274,
		name: "Sekolah Tinggi Ilmu Adm, Ujung Pandang",
		city: "Makassar",
		province: "Sulawesi Selatan",
	},
	{
		code: 273,
		name: "Akademi Teknik Keselamatan Penerbangan (ATKP) Makasar",
		city: "Kota Makassar",
		province: "Sulawesi Selatan",
	},
	{
		code: 272,
		name: "IAIN Palopo, Palopo",
		city: "Kota Palopo",
		province: "Sulawesi Selatan",
	},
	{
		code: 271,
		name: "STAIN Parepare, Parepare",
		city: "Kota Pare-pare",
		province: "Sulawesi Selatan",
	},
	{
		code: 270,
		name: "STAIN Watampone, Bone",
		city: "Kab. Bone",
		province: "Sulawesi Selatan",
	},
	{
		code: 269,
		name: "UIN Alauddin, Makassar",
		city: "Kab. Gowa",
		province: "Sulawesi Selatan",
	},
	{
		code: 268,
		name: "Universitas Islam Negeri Makassar",
		city: "Kota Makassar",
		province: "Sulawesi Selatan",
	},
	{
		code: 267,
		name: "Politeknik Negeri Media Kreatif, Kampus Makassar",
		city: "Kota Makassar",
		province: "Sulawesi Selatan",
	},
	{
		code: 266,
		name: "Universitas Maiwa Enrekang",
		city: "",
		province: "",
	},
	{
		code: 265,
		name: "Politeknik Negeri Ujung pandang, Makassar",
		city: "Kota Makassar",
		province: "Sulawesi Selatan",
	},
	{
		code: 264,
		name: "Politeknik Pertanian Negeri Pangkajene Kepulauan, Pangkajene Kepulauan",
		city: "Kab. Pangkajene Kepulauan",
		province: "Sulawesi Selatan",
	},
	{
		code: 263,
		name: "Universitas Negeri Makassar",
		city: "Kota Makassar",
		province: "Sulawesi Selatan",
	},
	{
		code: 262,
		name: "Universitas Hasanuddin, Makassar",
		city: "Kota Makassar",
		province: "Sulawesi Selatan",
	},
	{
		code: 261,
		name: "Politeknik Kesehatan Kemenkes Makassar, Makassar",
		city: "Kota Makassar",
		province: "Sulawesi Selatan",
	},
	{
		code: 260,
		name: "STAIN Datokarama, Palu",
		city: "Kota Palu",
		province: "Sulawesi Tengah",
	},
	{
		code: 259,
		name: "IAIN Datokarama, Palu",
		city: "Kota Palu",
		province: "Sulawesi Tengah",
	},
	{
		code: 258,
		name: "Sekolah Tinggi Ilmu Ekonomi (YPP Mujahidin), Tolitoli",
		city: "Kab. Toli-toli",
		province: "Sulawesi Tengah",
	},
	{
		code: 257,
		name: "Universitas Tadulako, Palu",
		city: "Kota Palu",
		province: "Sulawesi Tengah",
	},
	{
		code: 256,
		name: "IAIN Sultan Amai, Gorontalo",
		city: "Kota Gorontalo",
		province: "Gorontalo",
	},
	{
		code: 255,
		name: "Universitas Negeri Gorontalo, Gorontalo",
		city: "Kota Gorontalo",
		province: "Gorontalo",
	},
	{
		code: 254,
		name: "Politeknik Negeri Manado",
		city: "Kota Manado",
		province: "Sulawesi Utara",
	},
	{
		code: 253,
		name: "Politeknik Kesehatan Manado",
		city: "Kota Manado",
		province: "Sulawesi Utara",
	},
	{
		code: 252,
		name: "IAIN Manado, Manado (Sulawesi Utara)",
		city: "Kota Manado",
		province: "Sulawesi Utara",
	},
	{
		code: 251,
		name: "Politeknik Negeri Nusa Utara, Tahuna",
		city: "Kab. Kep. Sangihe",
		province: "Sulawesi Utara",
	},
	{
		code: 250,
		name: "Politeknik Negeri Manado, Manado",
		city: "Kota Manado",
		province: "Sulawesi Utara",
	},
	{
		code: 249,
		name: "Universitas Negeri Manado, Manado",
		city: "Kab. Minahasa",
		province: "Sulawesi Utara",
	},
	{
		code: 248,
		name: "Universitas Sam Ratulangi, Manado",
		city: "Kota Manado",
		province: "Sulawesi Utara",
	},
	{
		code: 247,
		name: "Universitas Borneo Tarakan",
		city: "Kota Tarakan",
		province: "Kalimantan Utara",
	},
	{
		code: 246,
		name: "IAIN Samarinda, Samarinda",
		city: "Kota Samarinda",
		province: "Kalimantan Timur",
	},
	{
		code: 245,
		name: "Politeknik Balikpapan, Balikpapan",
		city: "Kota Balikpapan",
		province: "Kalimantan Timur",
	},
	{
		code: 244,
		name: "Universitas Borneo Tarakan, Tarakan",
		city: "Kota Tarakan",
		province: "Kalimantan Utara",
	},
	{
		code: 243,
		name: "Politeknik Pertanian Negeri Samarinda, Samarinda",
		city: "Kota Samarinda",
		province: "Kalimantan TImur",
	},
	{
		code: 242,
		name: "Politeknik Negeri Samarinda, Samarinda",
		city: "Kota Samarinda",
		province: "Kalimantan Timur",
	},
	{
		code: 241,
		name: "Universitas Mulawarman, Samarinda",
		city: "Kota Samarinda",
		province: "Kalimantan Timur",
	},
	{
		code: 240,
		name: "Politeknik Pertanian Negeri Samarinda",
		city: "Kota Samarinda",
		province: "Kalimantan Timur",
	},
	{
		code: 239,
		name: "Poltekkes Banjarmasin",
		city: "Kota Banjarbaru",
		province: "Kalimantan Selatan",
	},
	{
		code: 238,
		name: "UIN Antasari Banjarmasin",
		city: "Kota Banjarmasin",
		province: "Kalimantan Selatan",
	},
	{
		code: 237,
		name: "Politeknik Negeri Banjarmasin, Banjarmasin",
		city: "Kota Banjarmasin",
		province: "Kalimantan Selatan",
	},
	{
		code: 236,
		name: "Universitas Lambung Mangkurat, Banjarmasin",
		city: "Kota Banjarmasin",
		province: "Kalimantan Selatan",
	},
	{
		code: 235,
		name: "Sekolah Tinggi Agama Kristen Negeri (STAKN) Palangkaraya (IAKN Palangka Raya)",
		city: "Kota Palangkaraya",
		province: "Kalimantan Tengah",
	},
	{
		code: 234,
		name: "Sekolah Tinggi Agama Hindu Negeri Tampung Peyang, Palangka Raya",
		city: "Kota Palangkaraya",
		province: "Kalimantan Tengah",
	},
	{
		code: 233,
		name: "IAIN Palangkaraya, Palangkaraya",
		city: "Kota Palangkaraya",
		province: "Kalimantan Tengah",
	},
	{
		code: 232,
		name: "Universitas Palangka Raya, Palangka Raya",
		city: "Kota Palangkaraya",
		province: "Kalimantan Tengah",
	},
	{
		code: 231,
		name: "IAIN Pontianak sebelumnya STAIN Pontianak",
		city: "Kota Pontianak",
		province: "Kalimantan Barat",
	},
	{
		code: 230,
		name: "Politeknik Tunas Bangsa",
		city: "",
		province: "",
	},
	{
		code: 229,
		name: "Politeknik Ketapang",
		city: "Kab. Ketapang",
		province: "Kalimantan Barat",
	},
	{
		code: 228,
		name: "Politeknik Tonggak Equator",
		city: "Kota Pontianak",
		province: "Kalimantan Barat",
	},
	{
		code: 227,
		name: "Politeknik Terpikat Sambas",
		city: "Kab. Sambas",
		province: "Kalimantan Barat",
	},
	{
		code: 226,
		name: "Politeknik Kesehatan Kementerian Kesehatan, Pontianak",
		city: "Kota Pontianak",
		province: "Kalimantan Barat",
	},
	{
		code: 225,
		name: "Politeknik Negeri Pontianak, Pontianak",
		city: "Kota Pontianak",
		province: "Kalimantan Barat",
	},
	{
		code: 224,
		name: "Universitas Tanjungpura, Pontianak",
		city: "Kota Pontianak",
		province: "Kalimantan Barat",
	},
	{
		code: 223,
		name: "Politeknik Kesehatan Denpasar",
		city: "Kota Denpasar",
		province: "Bali",
	},
	{
		code: 222,
		name: "Sekolah Tinggi Agama Kristen Negeri (STAKN) Denpasar",
		city: "Kota Denpasar",
		province: "Bali",
	},
	{
		code: 221,
		name: "Sekolah Tinggi Pariwisata Bali",
		city: "Kota Denpasar",
		province: "Bali",
	},
	{
		code: 220,
		name: "Akademi Kebidanan Pemprov Bali singaraja",
		city: "Kab. Buleleng",
		province: "Bali",
	},
	{
		code: 219,
		name: "Institut Hindu Dharma Negeri (IHDN) Denpasar",
		city: "Kota Denpasar",
		province: "Bali",
	},
	{
		code: 218,
		name: "Politeknik Negeri Tanah Lot",
		city: "",
		province: "",
	},
	{
		code: 217,
		name: "Institut Seni Indonesia Denpasar, Denpasar",
		city: "Kota Denpasar",
		province: "Bali",
	},
	{
		code: 216,
		name: "Politeknik Negeri Bali, Kuta-Badung",
		city: "Kab. Badung",
		province: "Bali",
	},
	{
		code: 215,
		name: "Universitas Pendidikan Ganesha, Singaraja",
		city: "Kab. Buleleng",
		province: "Bali",
	},
	{
		code: 214,
		name: "Universitas Udayana, Denpasar",
		city: "Kab. Badung",
		province: "Bali",
	},
	{
		code: 213,
		name: "Politeknik Pertanian Negeri Kupang, Kupang",
		city: "Kota Kupang",
		province: "Nusa Tenggara Timur",
	},
	{
		code: 212,
		name: "Politeknik Negeri Kupang, Kupang",
		city: "Kota Kupang",
		province: "Nusa Tenggara Timur",
	},
	{
		code: 211,
		name: "Universitas Nusa Cendana, Kupang",
		city: "Kota Kupang",
		province: "Nusa Tenggara Timur",
	},
	{
		code: 210,
		name: "Sekolah Tinggi Agama Hindu Negeri (STAHN) Gde Puja, Mataram",
		city: "Kota Mataram",
		province: "Nusa Tenggara Barat",
	},
	{
		code: 209,
		name: "IAIN Mataram, Lombok",
		city: "Kota Mataram",
		province: "Nusa Tenggara Barat",
	},
	{
		code: 208,
		name: "Universitas Mataram, Mataram",
		city: "Kota Mataram",
		province: "Nusa Tenggara Barat",
	},
	{
		code: 207,
		name: "Akademi TKP Ã¢â‚¬â€œ Surabaya",
		city: "Kota Surabaya",
		province: "Jawa Timur",
	},
	{
		code: 206,
		name: "Politeknik Pertanian Negeri Jember",
		city: "Kab. Jember",
		province: "Jawa Timur",
	},
	{
		code: 205,
		name: "Politeknik Kesehatan Surabaya",
		city: "Kota Surabaya",
		province: "Jawa Timur",
	},
	{
		code: 204,
		name: "Politeknik Kesehatan Malang",
		city: "Kota Malang",
		province: "Jawa Timur",
	},
	{
		code: 203,
		name: "Politeknik Elektronika Negeri Surabaya",
		city: "Kota Surabaya",
		province: "Jawa Timur",
	},
	{
		code: 202,
		name: "IAIN Jember, Jember",
		city: "Kab. Jember",
		province: "Jawa Timur",
	},
	{
		code: 201,
		name: "Sekolah Tinggi Penyuluhan Pertanian (STTP) Malang",
		city: "Kab. Malang",
		province: "Jawa Timur",
	},
	{
		code: 200,
		name: "Teknik Keselamatan Penerbangan (ATKP) Surabaya",
		city: "Kota Surabaya",
		province: "Jawa Timur",
	},
	{
		code: 199,
		name: "Akademi Angkatan Laut (AAL), Surabaya",
		city: "Kota Surabaya",
		province: "Jawa Timur",
	},
	{
		code: 198,
		name: "STAIN Pamekasan, Pamekasan",
		city: "Kab. Pamekasan",
		province: "Jawa Timur",
	},
	{
		code: 197,
		name: "UIN Maulana Malik Ibrahim, Malang",
		city: "Kota Malang",
		province: "Jawa Timur",
	},
	{
		code: 196,
		name: "IAIN Tulungagung",
		city: "Kab. Tulungagung",
		province: "Jawa Timur",
	},
	{
		code: 195,
		name: "UIN Sunan Ampel",
		city: "Kota Surabaya",
		province: "Jawa Timur",
	},
	{
		code: 194,
		name: "Institut Agama Islam Negeri (IAIN) Ponorogo, Ponorogo",
		city: "Kab. Ponorogo",
		province: "Jawa Timur",
	},
	{
		code: 193,
		name: "STAIN Kediri",
		city: "Kota Kediri",
		province: "Jawa Timur",
	},
	{
		code: 192,
		name: "Universitas Islam Negeri Maulana Malik Ibrahim, Malang",
		city: "Kota Malang",
		province: "Jawa Timur",
	},
	{
		code: 191,
		name: "Akademi Komunitas Negeri Bojonegoro, Bojonegoro",
		city: "Kab. Bojonegoro",
		province: "Jawa Timur",
	},
	{
		code: 190,
		name: "Akademi Komunitas Negeri Sumenep. Sumenep",
		city: "Kab. Sumenep",
		province: "Jawa Timur",
	},
	{
		code: 189,
		name: "Akademi Komunitas Negeri Lamongan, Lamongan",
		city: "Kab. Lamongan",
		province: "Jawa Timur",
	},
	{
		code: 188,
		name: "Politeknik Negeri Banyuwangi, Banyuwangi",
		city: "Kab. Banyuwangi",
		province: "Jawa Timur",
	},
	{
		code: 187,
		name: "Universitas Pembangunan Nasional Veteran (UPN), Surabaya",
		city: "Kota Surabaya",
		province: "Jawa Timur",
	},
	{
		code: 186,
		name: "Akademi Komunitas Negeri, Pacitan",
		city: "Kab. Pacitan",
		province: "Jawa Timur",
	},
	{
		code: 185,
		name: "Akademi Komunitas Negeri, Bojonegoro",
		city: "Kab. Bojonegoro",
		province: "Jawa Timur",
	},
	{
		code: 184,
		name: "Institut Teknologi Sepuluh Nopember, Surabaya",
		city: "Kota Surabaya",
		province: "Jawa Timur",
	},
	{
		code: 183,
		name: "Politeknik Negeri Jember, Jember",
		city: "Kab. Jember",
		province: "Jawa Timur",
	},
	{
		code: 182,
		name: "Politeknik Negeri Madiun, Madiun",
		city: "Kota Madiun",
		province: "Jawa Timur",
	},
	{
		code: 181,
		name: "Politeknik Negeri Malang, Malang",
		city: "Kota Malang",
		province: "Jawa Timur",
	},
	{
		code: 180,
		name: "Politeknik Negeri Madura, Sampang",
		city: "Kab. Sampang",
		province: "Jawa Timur",
	},
	{
		code: 179,
		name: "Politeknik Perkapalan Negeri Surabaya, Surabaya",
		city: "Kota Surabaya",
		province: "Jawa Timur",
	},
	{
		code: 178,
		name: "Politeknik Elektronika Negeri Surabaya, Surabaya",
		city: "Kota Surabaya",
		province: "Jawa Timur",
	},
	{
		code: 177,
		name: "Universitas Trunojoyo, Bangkalan",
		city: "Kab. Bangkalan",
		province: "Jawa Timur",
	},
	{
		code: 176,
		name: "Universitas Jember, Jember",
		city: "Kab. Jember",
		province: "Jawa Timur",
	},
	{
		code: 175,
		name: "Universitas Negeri Malang, Malang",
		city: "Kota Malang",
		province: "Jawa Timur",
	},
	{
		code: 174,
		name: "Universitas Brawijaya, Malang",
		city: "Kota Malang",
		province: "Jawa Timur",
	},
	{
		code: 173,
		name: "Universitas Negeri Surabaya, Surabaya",
		city: "Kota Surabaya",
		province: "Jawa Timur",
	},
	{
		code: 172,
		name: "Universitas Airlangga, Surabaya",
		city: "Kota Surabaya",
		province: "Jawa Timur",
	},
	{
		code: 171,
		name: "Politeknik Kesehatan Yogyakarta",
		city: "Kab. Sleman",
		province: "D.I. Yogyakarta",
	},
	{
		code: 170,
		name: "Sekolah Tinggi Teknologi Nuklir (STTN), Yogyakarta",
		city: "Kab. Sleman",
		province: "D.I. Yogyakarta",
	},
	{
		code: 169,
		name: "Sekolah Tinggi Pertanahan Nasional (STPN), Yogyakarta",
		city: "Kab. Sleman",
		province: "D.I. Yogyakarta",
	},
	{
		code: 168,
		name: "Akademi Angkatan Udara (AAU), Yogyakarta",
		city: "Kota Yogyakarta",
		province: "D.I. Yogyakarta",
	},
	{
		code: 167,
		name: "UIN Sunan Kalijaga",
		city: "Kab. Sleman",
		province: "D.I. Yogyakarta",
	},
	{
		code: 166,
		name: "Universitas Pembangunan Nasional Veteran (UPN), Yogyakarta",
		city: "Kab. Sleman",
		province: "D.I. Yogyakarta",
	},
	{
		code: 165,
		name: "Akademi Teknologi Kulit Yogyakarta (ATK)",
		city: "Kab. Bantul",
		province: "D.I. Yogyakarta",
	},
	{
		code: 164,
		name: "Universita Terbuka UPBJJ Yogyakarta",
		city: "Kota Yogyakarta",
		province: "D.I. Yogyakarta",
	},
	{
		code: 163,
		name: "Institut Seni Indonesia Yogyakarta",
		city: "Kab. Bantul",
		province: "D.I. Yogyakarta",
	},
	{
		code: 162,
		name: "Universitas Negeri Yogyakarta",
		city: "Kab. Sleman",
		province: "D.I. Yogyakarta",
	},
	{
		code: 161,
		name: "Universitas Gadjah Mada",
		city: "Kab. Sleman",
		province: "D.I. Yogyakarta",
	},
	{
		code: 160,
		name: "Politeknik Kesehatan Surakarta",
		city: "Kota Surakarta",
		province: "Jawa Tengah",
	},
	{
		code: 159,
		name: "Politeknik Kesehatan Semarang",
		city: "Kota Semarang",
		province: "Jawa Tengah",
	},
	{
		code: 158,
		name: "Politeknik Ilmu Pelayaran Semarang",
		city: "Kota Semarang",
		province: "Jawa Tengah",
	},
	{
		code: 157,
		name: "Sekolah Tinggi Penyuluhan Pertanian (STTP) Magelang",
		city: "Kab. Magelang",
		province: "Jawa Tengah",
	},
	{
		code: 156,
		name: "Sekolah Tinggi Seni Indonesia (STSI), Surakarta",
		city: "Kota Surakarta",
		province: "Jawa Tengah",
	},
	{
		code: 155,
		name: "Akademi Sanitasi dan Kesehatan Lingkungan (ASKK), Purwokerto",
		city: "Kota Purwokerto",
		province: "Jawa Tengah",
	},
	{
		code: 154,
		name: "Akademi Minyak dan Gas Bumi (AKAMIGAS), Blora",
		city: "Kab. Blora",
		province: "Jawa Tengah",
	},
	{
		code: 153,
		name: "Akademi Militer (AKMIL) TNI AD, Magelang",
		city: "Kota Magelang",
		province: "Jawa Tengah",
	},
	{
		code: 152,
		name: "Akademi Kepolisian (AKPOL),Semarang",
		city: "Kota Semarang",
		province: "Jawa Tengah",
	},
	{
		code: 151,
		name: "IAIN Purwokerto, Purwokerto",
		city: "Kab. Banyumas",
		province: "Jawa Tengah",
	},
	{
		code: 150,
		name: "IAIN Salatiga, Salatiga",
		city: "Kota Salatiga",
		province: "Jawa Tengah",
	},
	{
		code: 149,
		name: "STAIN Pekalongan, Pekalongan",
		city: "Kota Pekalongan",
		province: "Jawa Tengah",
	},
	{
		code: 148,
		name: "Institut Agama Islam Negeri (IAIN) Kudus, Kudus",
		city: "Kab. Kudus",
		province: "Jawa Tengah",
	},
	{
		code: 147,
		name: "IAIN Surakarta, Surakarta",
		city: "Kab. Sukoharjo",
		province: "Jawa Tengah",
	},
	{
		code: 146,
		name: "UIN Walisongo, Semarang",
		city: "Kota Semarang",
		province: "Jawa Tengah",
	},
	{
		code: 145,
		name: "Universitas Tidar Magelang, Magelang",
		city: "Kota Magelang",
		province: "Jawa Tengah",
	},
	{
		code: 144,
		name: "Institut Seni Indonesia Surakarta, Surakarta (ISI Solo, dahulu STSI)",
		city: "Kota Surakarta",
		province: "Jawa Tengah",
	},
	{
		code: 143,
		name: "Politeknik Maritim Negeri Indonesia, Semarang",
		city: "Kota Semarang",
		province: "Jawa Tengah",
	},
	{
		code: 142,
		name: "Politeknik Negeri Semarang, Semarang",
		city: "Kota Semarang",
		province: "Jawa Tengah",
	},
	{
		code: 141,
		name: "Universitas Surakarta Sebelas Maret (UNS), Surakarta",
		city: "Kota Surakarta",
		province: "Jawa Tengah",
	},
	{
		code: 140,
		name: "Universitas Jenderal Soedirman, Purwokerto",
		city: "Kab. Banyumas",
		province: "Jawa Tengah",
	},
	{
		code: 139,
		name: "Universitas Negeri Semarang, Semarang",
		city: "Kota Semarang",
		province: "Jawa Tengah",
	},
	{
		code: 138,
		name: "Universitas Diponegoro, Semarang",
		city: "Kota Semarang",
		province: "Jawa Tengah",
	},
	{
		code: 137,
		name: "Politeknik Negeri Bali, Badung",
		city: "Kab. Badung",
		province: "Bali",
	},
	{
		code: 136,
		name: "Politeknik Manufaktur Bandung",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 135,
		name: "Politeknik Kesehatan Kemenkes (Poltekkes) Bandung",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 134,
		name: "STAIN Cirebon",
		city: "Kota Cirebon",
		province: "Jawa Barat",
	},
	{
		code: 133,
		name: "Sekolah Tinggi Penyuluhan Pertanian (STTP) Bogor",
		city: "Kota Bogor",
		province: "Jawa Barat",
	},
	{
		code: 132,
		name: "Sekolah Tinggi Pemerintahan Dalam Negeri (STPDN), Sumedang",
		city: "Kab. Sumedang",
		province: "Jawa Barat",
	},
	{
		code: 131,
		name: "Sekolah Tinggi Kesejahteraan Sosial (STKS), Bandung",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 130,
		name: "Sekolah Tinggi Transportasi Darat (STTD), Bekasi",
		city: "Kab. Bekasi",
		province: "Jawa Barat",
	},
	{
		code: 129,
		name: "Institut Seni Budaya Indonesia (ISBI) Bandung",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 128,
		name: "Sekolah Tinggi Sandi Negara (STSN), Bogor",
		city: "Kab. Bogor",
		province: "Jawa Barat",
	},
	{
		code: 127,
		name: "Sekolah Tinggi Ilmu Administrasi, Bandung",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 126,
		name: "Akademi Kimia Analis (AKA) Bogor",
		city: "Kota Bogor",
		province: "Jawa Barat",
	},
	{
		code: 125,
		name: "Akademi Imigrasi (AIM) Depok",
		city: "Kota Depok",
		province: "Jawa Barat",
	},
	{
		code: 124,
		name: "Akademi Ilmu Pemasyarakatan (AKIP), Depok",
		city: "Kota Depok",
		province: "Jawa Barat",
	},
	{
		code: 123,
		name: "Universitas Pendidikan Indonesia, Kampus Daerah Purwakarta",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 122,
		name: "Universitas Pendidikan Indonesia, Kampus Daerah Sumedang",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 121,
		name: "Universitas Pendidikan Indonesia, Kampus Daerah Tasikmalaya",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 120,
		name: "Universitas Pendidikan Indonesia, Kampus Daerah Cibiru",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 119,
		name: "Universitas Swadaya Gunung Jati (Unswagati) di Kota Cirebon",
		city: "Kota Cirebon",
		province: "Jawa Barat",
	},
	{
		code: 118,
		name: "Universitas Singaperbangsa (UNSIKA), Kampus Daerah Karawang",
		city: "Kab. Karawang",
		province: "Jawa Barat",
	},
	{
		code: 117,
		name: "Universitas Siliwangi (UNSIL), Tasikmalaya",
		city: "Kota Tasikmalaya",
		province: "Jawa Barat",
	},
	{
		code: 116,
		name: "Politeknik Indramayu, Indramayu",
		city: "Kab. Indramayu",
		province: "Jawa Barat",
	},
	{
		code: 115,
		name: "Politeknik Negeri Bandung, Bandung",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 114,
		name: "Institut Teknologi Bandung, Bandung",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 113,
		name: "Institut Pertanian Bogor, Bogor",
		city: "Kab. Bogor",
		province: "Jawa Barat",
	},
	{
		code: 112,
		name: "Universitas Jenderal Achmad Yani, Bandung",
		city: "Kota Cimahi",
		province: "Jawa Barat",
	},
	{
		code: 111,
		name: "Universitas Padjadjaran, Bandung",
		city: "Kab. Sumedang",
		province: "Jawa Barat",
	},
	{
		code: 110,
		name: "Universitas Pendidikan Indonesia, Bandung",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 109,
		name: "Politeknik Manufaktur Negeri Bandung, Bandung",
		city: "Kota Bandung",
		province: "Jawa Barat",
	},
	{
		code: 108,
		name: "Politeknik Negeri Jakarta",
		city: "Kota Depok",
		province: "Jawa Barat",
	},
	{
		code: 107,
		name: "Politeknik Kesehatan Jakarta II",
		city: "Kota Jakarta Selatan",
		province: "D.K.I. Jakarta",
	},
	{
		code: 106,
		name: "Politeknik Kesehatan Jakarta I",
		city: "Kota Jakarta Selatan",
		province: "D.K.I. Jakarta",
	},
	{
		code: 105,
		name: "Sekolah Tinggi Perikanan (STP), Jakarta",
		city: "Kota Jakarta Selatan",
		province: "D.K.I. Jakarta",
	},
	{
		code: 104,
		name: "Sekolah Tinggi Penerbangan Indonesia (PI), Jakarta",
		city: "Kota Jakarta Selatan",
		province: "D.K.I. Jakarta",
	},
	{
		code: 103,
		name: "Sekolah Tinggi Manajemen Industri(STMI), Jakarta",
		city: "Kota Jakarta Pusat",
		province: "D.K.I. Jakarta",
	},
	{
		code: 102,
		name: "Sekolah Tinggi Ilmu Statistik (STIS), Jakarta",
		city: "Kota Jakarta Timur",
		province: "D.K.I. Jakarta",
	},
	{
		code: 101,
		name: "Sekolah Tinggi Ilmu Pelayaran (STIP), Jakarta",
		city: "Kota Jakarta Utara",
		province: "D.K.I. Jakarta",
	},
	{
		code: 100,
		name: "Sekolah Tinggi Ilmu Kepolisian (PTIK), Jakarta",
		city: "Kota Jakarta Selatan",
		province: "D.K.I. Jakarta",
	},
	{
		code: 99,
		name: "Sekolah Tinggi Ilmu Administrasi, LAN Jakarta",
		city: "Kota Jakarta Pusat",
		province: "D.K.I. Jakarta",
	},
	{
		code: 98,
		name: "Sekolah Tinggi Hukum Militer, STHM",
		city: "Kota Jakarta Timur",
		province: "D.K.I. Jakarta",
	},
	{
		code: 97,
		name: "Politeknik Keuangan Negara STAN",
		city: "Kota Tangerang Selatan",
		province: "Banten",
	},
	{
		code: 96,
		name: "Institut Ilmu Pemerintahan, IIP, Jakarta",
		city: "Kota Jakarta Selatan",
		province: "DKI Jakarta",
	},
	{
		code: 95,
		name: "Akademi Pimpinan Perusahaan (APP), Jakarta",
		city: "Kota Jakarta Selatan",
		province: "DKI Jakarta",
	},
	{
		code: 94,
		name: "Sekolah Tinggi Manajemen Industri Indonesia",
		city: "Kota Jakarta Pusat",
		province: "DKI Jakarta",
	},
	{
		code: 93,
		name: "Sekolah Tinggi Ilmu Pelayaran Jakarta",
		city: "Kota Jakarta Utara",
		province: "DKI Jakarta",
	},
	{
		code: 92,
		name: "UIN Syarif Hidayatullah, Jakarta",
		city: "Kota Tangerang Selatan",
		province: "Banten",
	},
	{
		code: 91,
		name: "Politeknik Negeri Media Kreatif, Jakarta",
		city: "Kota Jakarta Selatan",
		province: "DKI Jakarta",
	},
	{
		code: 90,
		name: "Politeknik Negeri Jakarta",
		city: "Kota Depok",
		province: "Jawa Barat",
	},
	{
		code: 89,
		name: "Universitas Terbuka",
		city: "Kota Tangerang Selatan",
		province: "Banten",
	},
	{
		code: 88,
		name: "Universitas Negeri Jakarta",
		city: "Kota Jakarta Timur",
		province: "DKI Jakarta",
	},
	{
		code: 87,
		name: "Universitas Pertahanan Indonesia (UNHAN)",
		city: "Bogor",
		province: "Jawa Barat",
	},
	{
		code: 86,
		name: "Universitas Indonesia",
		city: "Kota Depok",
		province: "Jawa Barat",
	},
	{
		code: 85,
		name: "Institut Agama Islam Banten (IAIB)",
		city: "Kota Serang",
		province: "Banten",
	},
	{
		code: 84,
		name: "Akademi Meteorologi dan Geofisika (AMG) Tangerang",
		city: "Kota Tangerang Selatan",
		province: "Banten",
	},
	{
		code: 83,
		name: "Sekolah Tinggi Agama Buddha Negeri Sriwijaya Tangerang",
		city: "Kota Tangerang",
		province: "Banten",
	},
	{
		code: 82,
		name: "Universitas Terbuka Pondok Cabe",
		city: "Kota Tangerang Selatan",
		province: "Banten",
	},
	{
		code: 81,
		name: "Universitas Pendidikan Indonesia, Kampus Daerah Serang",
		city: "Kota Serang",
		province: "Banten",
	},
	{
		code: 80,
		name: "IAIN Sultan Maulana Hasanuddin",
		city: "Kota Serang",
		province: "Banten",
	},
	{
		code: 79,
		name: "Perguruan Tinggi Buddhi, Karawaci",
		city: "Kota Tangerang",
		province: "Banten",
	},
	{
		code: 78,
		name: "Universitas Sultan Ageng Tirtayasa, Serang",
		city: "Kota Serang",
		province: "Banten",
	},
	{
		code: 77,
		name: "STAIN Syekh Abdurrahman Siddik, Bangka Belitung",
		city: "Kab. Bangka",
		province: "Kepulauan Bangka Belitung",
	},
	{
		code: 76,
		name: "Poltekkes Kemenkes Pangkal Pinang, Bangka Belitung",
		city: "Kab. Bangka Tengah",
		province: "Kepulauan Bangka Belitung",
	},
	{
		code: 75,
		name: "Politeknik Manufaktur, Bangka Belitung",
		city: "Kab. Bangka",
		province: "Kepulauan Bangka Belitung",
	},
	{
		code: 74,
		name: "Universitas Bangka Belitung, Bangka Belitung",
		city: "Pangkal Pinang",
		province: "Kepulauan Bangka Belitung",
	},
	{
		code: 73,
		name: "IAIN Raden Intan, Bandar Lampung",
		city: "Kota Bandar Lampung",
		province: "Lampung",
	},
	{
		code: 72,
		name: "STAIN Jurai Siwo Metro",
		city: "Kota Metro",
		province: "Lampung",
	},
	{
		code: 71,
		name: "Institut Agama Islam Negeri Raden Intan, Bandar Lampung",
		city: "Kota Bandar Lampung",
		province: "Lampung",
	},
	{
		code: 70,
		name: "STIM (Sekolah Tinggi Olahraga Metro), Kota Metro",
		city: "Kota Metro",
		province: "Lampung",
	},
	{
		code: 69,
		name: "Poltekkes Kemenkes Tanjungkarang, Bandar Lampung",
		city: "Kab. Lampung Selatan",
		province: "Lampung",
	},
	{
		code: 68,
		name: "Politeknik Negeri Lampung, Bandar Lampung",
		city: "Kota Bandar Lampung",
		province: "Lampung",
	},
	{
		code: 67,
		name: "Universitas Lampung, Bandar Lampung",
		city: "Kota Bandar Lampung",
		province: "Lampung",
	},
	{
		code: 66,
		name: "Universitas Islam Negeri (UIN) Raden Fatah Palembang",
		city: "Kota Palembang",
		province: "Sumatera Selatan",
	},
	{
		code: 65,
		name: "Akademi Komunitas Negeri Prabumulih, Prabumulih",
		city: "Kota Prabumulih",
		province: "Sumatera Selatan",
	},
	{
		code: 64,
		name: "Poltekkes depkes Palembang, Palembang",
		city: "Kota Palembang",
		province: "Sumatera Selatan",
	},
	{
		code: 62,
		name: "Universitas Sriwijaya, Palembang",
		city: "Kota Palembang",
		province: "Sumatera Selatan",
	},
	{
		code: 61,
		name: "STAIN Curup, Rejang Lebong",
		city: "Kab. Rejang Lebong",
		province: "Bengkulu",
	},
	{
		code: 60,
		name: "Poltekkes Kemenkes Bengkulu",
		city: "Kota Bengkulu",
		province: "Bengkulu",
	},
	{
		code: 59,
		name: "STAIN CURUP",
		city: "Kab. Rejang Lebong",
		province: "Bengkulu",
	},
	{
		code: 58,
		name: "IAIN Bengkulu",
		city: "Kota Bengkulu",
		province: "Bengkulu",
	},
	{
		code: 57,
		name: "Universitas Bengkulu, Bengkulu",
		city: "Kota Bengkulu",
		province: "Bengkulu",
	},
	{
		code: 56,
		name: "Politeknik Kesehatan Jambi",
		city: "Kota Jambi",
		province: "Jambi",
	},
	{
		code: 55,
		name: "Universitas Islam Negeri (UIN) Sultan Thaha Saifuddin Jambi",
		city: "Kota Jambi",
		province: "Jambi",
	},
	{
		code: 54,
		name: "STAIN Kerinci",
		city: "Kab. Kerinci",
		province: "Jambi",
	},
	{
		code: 53,
		name: "Universitas Jambi, Jambi",
		city: "Kab. Muaro Jambi",
		province: "Jambi",
	},
	{
		code: 52,
		name: "STAIN Bengkalis, Riau (Riau)",
		city: "Kab. Bengkalis",
		province: "Riau",
	},
	{
		code: 50,
		name: "Politeknik Negeri Batam",
		city: "Kota Batam",
		province: "Kepulauan Riau",
	},
	{
		code: 49,
		name: "Universitas Maritim Raja Ali Haji",
		city: "Kota Tanjung Pinang",
		province: "Kepulauan Riau",
	},
	{
		code: 48,
		name: "Politeknik Negeri Bengkalis",
		city: "Bengkalis",
		province: "Riau",
	},
	{
		code: 47,
		name: "Universitas Islam Negeri Syarif Kasim (UIN SUSKA), Riau",
		city: "Pekan Baru",
		province: "Riau",
	},
	{
		code: 46,
		name: "Universitas Riau, Pekanbaru",
		city: "Pekan Baru",
		province: "Riau",
	},
	{
		code: 45,
		name: "Politeknik Negeri Sriwijaya (POLSRI), Palembang",
		city: "Kota Palembang",
		province: "Sumatera Selatan",
	},
	{
		code: 44,
		name: "STAIN Sjech M. Djamil Djambek , Bukittinggi",
		city: "Bukittinggi",
		province: "Sumatera Barat",
	},
	{
		code: 43,
		name: "IAIN Imam Bonjol, Padang",
		city: "Kota Padang",
		province: "Sumatera Barat",
	},
	{
		code: 42,
		name: "ISI Padang Panjang",
		city: "Kota Padang Panjang",
		province: "Sumatera Barat",
	},
	{
		code: 41,
		name: "STAIN Bukittinggi",
		city: "Kab. Agam",
		province: "Bukittinggi",
	},
	{
		code: 40,
		name: "Institut Agama Islam Negeri (IAIN) Batusangkar",
		city: "Kab. Tanah Datar",
		province: "Sumatera Barat",
	},
	{
		code: 39,
		name: "IAIN Imam Bonjol, Padang",
		city: "Kota Padang",
		province: "Sumatera Barat",
	},
	{
		code: 38,
		name: "STSI (Sekolah Tinggi Seni Indonesia Padang Panjang), Padang Panjang",
		city: "Kota Padang Panjang",
		province: "Sumatera Barat",
	},
	{
		code: 37,
		name: "Politeknik Pertanian, Payakumbuh",
		city: "Kab. Limapuluh Kota",
		province: "Sumatera Barat",
	},
	{
		code: 36,
		name: "Politeknik Negeri Padang, Padang",
		city: "Padang",
		province: "Sumatera Barat",
	},
	{
		code: 35,
		name: "Universitas Negeri Padang, Padang",
		city: "Padang",
		province: "Sumatera Barat",
	},
	{
		code: 34,
		name: "Universitas Andalas, Padang",
		city: "Padang",
		province: "Sumatera Barat",
	},
	{
		code: 33,
		name: "Sekolah Tinggi Penyuluhan Pertanian Medan",
		city: "Medan",
		province: "Sumatera Utara",
	},
	{
		code: 32,
		name: "kademi Tek. Kes. Penerbangan (ATKP), Medan",
		city: "Medan",
		province: "Sumatera Utara",
	},
	{
		code: 30,
		name: "Sekolah Tinggi Penyuluhan Pertanian (STTP) Medan",
		city: "Medan",
		province: "Sumatera Utara",
	},
	{
		code: 29,
		name: "Sekolah Tinggi Agama Kristen Protestan Negeri Tarutung",
		city: "Kab. Tapanuli Utara",
		province: "Sumatera Utara",
	},
	{
		code: 28,
		name: "Akademi Teknik Keselamatan Penerbangan (ATKP) Medan",
		city: "Medan",
		province: "Sumatera Utara",
	},
	{
		code: 27,
		name: "IAIN Padang Sidempuan, Tapanuli Selatan",
		city: "Kota Padang Sidempuan",
		province: "Sumatera Utara",
	},
	{
		code: 26,
		name: "UIN Sumatera Utara, Medan",
		city: "Kab. Deli Serdang",
		province: "Sumatera Utara",
	},
	{
		code: 25,
		name: "STAIN Padang Sidempuan, Padang Sidempuan",
		city: "Kota Padang Sidempuan",
		province: "Sumatera Utara",
	},
	{
		code: 24,
		name: "Poltekes Depkes Medan, Medan",
		city: "Kota Medan",
		province: "Sumatera Utara",
	},
	{
		code: 23,
		name: "Institut Agama Islam Negeri Sumatera utara, Medan",
		city: "Kota Medan",
		province: "Sumatera Utara",
	},
	{
		code: 22,
		name: "Politeknik Negeri Media Kreatif, Medan",
		city: "Kota Medan",
		province: "Sumatera Utara",
	},
	{
		code: 21,
		name: "Politeknik Negeri Medan, Medan",
		city: "Kota Medan",
		province: "Sumatera Utara",
	},
	{
		code: 20,
		name: "Universitas Negeri Medan, Medan",
		city: "Kota Medan",
		province: "Sumatera Utara",
	},
	{
		code: 19,
		name: "Universitas Sumatera Utara, Medan",
		city: "Kota Medan",
		province: "Sumatera Utara",
	},
	{
		code: 18,
		name: "Universitas Serambi Mekkah",
		city: "Kota Banda Aceh",
		province: "Aceh",
	},
	{
		code: 17,
		name: "Politeknik Kesehatan Banda Aceh",
		city: "Kota Banda Aceh",
		province: "Aceh",
	},
	{
		code: 16,
		name: "STAIN Teungku Dirundeng, Melabuh",
		city: "Kab. Aceh Barat",
		province: "Aceh",
	},
	{
		code: 15,
		name: "STAIN Gajah Putih Takengon, Takengon",
		city: "Kab. Aceh Tengah",
		province: "Aceh",
	},
	{
		code: 14,
		name: "STAIN Malikussaleh, Lhokseumawe",
		city: "Kota Lhokseumawe",
		province: "Aceh",
	},
	{
		code: 13,
		name: "IAIN Langsa, Langsa",
		city: "Palangka Raya",
		province: "Aceh",
	},
	{
		code: 12,
		name: "STAIN Gajah Putih Takengon",
		city: "Kab. Aceh Tengah",
		province: "Aceh",
	},
	{
		code: 11,
		name: "Akademi Komunitas Negeri (AKN) Aceh Barat Daya",
		city: "Kab. Aceh Barat Daya",
		province: "Aceh",
	},
	{
		code: 10,
		name: "STAIN Zawiyah Cot Kala, Langsa",
		city: "Kota Langsa",
		province: "Aceh",
	},
	{
		code: 9,
		name: "STAIN Malikussaleh, Lhokseumawe",
		city: "Kota Lhokseumawe",
		province: "Aceh",
	},
	{
		code: 8,
		name: "UIN Ar-Raniry, Banda Aceh",
		city: "Kota Banda Aceh",
		province: "Aceh",
	},
	{
		code: 7,
		name: "Politeknik Aceh, Banda Aceh",
		city: "Kota Banda Aceh",
		province: "Aceh",
	},
	{
		code: 6,
		name: "Universitas Teuku Umar, Meulaboh",
		city: "Kab. Aceh Barat Daya",
		province: "Aceh",
	},
	{
		code: 5,
		name: "Universitas Samudra, Langsa",
		city: "Kota Langsa",
		province: "Aceh",
	},
	{
		code: 4,
		name: "Politeknik Negeri Aceh, Banda Aceh",
		city: "Kota Banda Aceh",
		province: "Aceh",
	},
	{
		code: 3,
		name: "Politeknik Negeri Lhokseumawe, Lhokseumawe",
		city: "Kota Lhokseumawe",
		province: "Aceh",
	},
	{
		code: 2,
		name: "Universitas Malikussaleh, Lhokseumawe",
		city: "Kab. Aceh Utara",
		province: "Aceh",
	},
	{
		code: 1,
		name: "Universitas Syiah Kuala, Banda Aceh",
		city: "Kota Banda Aceh",
		province: "Aceh",
	},
];

mongoose
	.connect(
		"mongodb+srv://datcen:7oRSPtqM2DlM2kbm@bmka-datacenter.nktj7.mongodb.net/achievement-board?retryWrites=true&w=majority",
		{
			useNewUrlParser: true,
			useUnifiedTopology: true,
		}
	)
	.catch((err) => console.log(err))
	.then(() => console.log("DB connected!"));

campuses.map(async (campus, index) => {
	const res = new Campus(campus);
	await res.save((err) => {
		if (index == campuses.length - 1) {
			console.log("Data seeded!");
			mongoose.disconnect();
		}
	});
});
